settings:
  title: 'BobsterJS Status'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Some Systems Are Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: bobsterjs-ml # unique identifier
    name: bobsterjs.ml
    url: 'https://www.bobsterjs.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200

  - id: weather-bobsterjs-ml # unique identifier
    name: weatheer.bobsterjs.ml
    url: 'https://weather.bobsterjs.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200

  - id: clock-bobsterjs-ml # unique identifier
    name: clock.bobsterjs.ml
    url: 'https://clock.bobsterjs.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200

  - id: stopwatch-bobsterjs-ml # unique identifier
    name: stopwatch.bobsterjs.ml
    url: 'https://stopwatch.bobsterjs.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200

  - id: social-bobsterjs-ml # unique identifier
    name: social.bobsterjs.ml
    url: 'https://social.bobsterjs.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200

  - id: digidev-bobsterjs-ml # unique identifier
    name: digitaldev.bobsterjs.ml
    url: 'https://digitaldev.bobsterjs.ml/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
